= Sociocortex Tutorial
Daniel Elsner <daniel.elsner@tum.de>
:toc: left
:source-highlighter: highlightjs

A hands-on tutorial for the https://sociocortex.com[sociocortex] REST API.

== Introduction

=== Motivation

What is sociocortex and explanation how the REST API is used to communicate with the platform in client applications.

=== Concepts
* Architecture (Layers)
* Class Hierarchy (Entities, Workspaces, Tasks, etc.)
* Basic types in sociocortex (Numbers, String, Enum, Date, etc.)
* Usage (server.sociocortex (CM?), REST API, sc-angular, modeler, visualizer) (?)

== Configuration
* Links to Bitbucket/Github repo
* Offline version: Sociocortex setup
* Online version: Authentication
** POSTMAN test-setup (create?!)

== Getting started with the REST API

=== Introduction to demo scenario

The demo scenario that will serve as a real world example to demonstrate the usage of the _sociocortex REST API_ is a simple publication management system.

Before we can start with the actual scenario, we check that the authentication is working for your credentials and shortly outline the differences of jwt and basic auth.

Once the authentication works, we create a workspace which we then use to store the required entity types in. We identify the required entity types as _publication_ and _conference_.
The latter we use to add entities, i.e. publications or conferences, to the workspace with respective entity types.

Furthermore, tasks and their definitions are introduced and combined with the attribute definitions of entity types.

While going through the demo scenario all HTTP verbs will be taken into account in order to make you feel comfortable with all kinds of actions necessary to interact with the _sociocortex REST API_.

=== TODO: Authentication
* Looking for existing users (GET)
* Sending requests with BASIC Auth
* Sending requests with JWT

=== Creating a workspace

Before creating our first workspace we check for the currently available workspaces because who know's, maybe someone else did the job for us already.

We do this with a simple HTTP GET request on the workspaces resource. The server will respond with a list of workspaces stored. Below you see the request and response.

==== Looking for existing workspaces (GET)

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/workspaces

*Response:*
[source,json]
[
  {
    "id": "944wcmiregxu",
    "name": "sc-visualizer",
    "href": "https://server.sociocortex.com/api/v1/workspaces/944wcmiregxu"
  },
  {
    "id": "107yhdgc7q9u6",
    "name": "Northwind",
    "href": "https://server.sociocortex.com/api/v1/workspaces/107yhdgc7q9u6"
  }
]

We can tell that no one has yet created a publication management workspace so we continue by creating one with a HTTP POST request.

==== Creating workspace _publication management_ (POST)

*Request:*
[source,json]
POST https://server.sociocortex.com/api/v1/workspaces
BODY
{
    "name": "Publication Management"
}

*Response:*
[source,json]
{
  "id": "10sasph8dvxhg",
  "versions": [
    {
      "action": "Edited",
      "date": "2016-07-15T17:06:42.012Z",
      "type": "_edit",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    },
    {
      "action": "Added",
      "date": "2016-07-15T17:06:41.371Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "rootEntity": {
    "id": "bqr7jmg37vqt",
    "name": "Publication Management - Home",
    "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt"
  },
  "mayCreateEntities": true,
  "isFavorite": false,
  "entityTree": {
    "id": "bqr7jmg37vqt",
    "name": "Publication Management - Home",
    "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt"
  },
  "name": "Publication Management",
  "permissions": {
    "contributors": [],
    "administrators": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ],
    "writers": [],
    "readers": []
  },
  "customFunctions": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
}

==== Looking at a single workspace (GET)

As we have seen in the response of the server on our POST request the workspace has been created with the id _10sasph8dvxhg_. We can easily use this id now to get this specific workspace.

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg

*Response:*
[source,json]
{
  "id": "10sasph8dvxhg",
  "versions": [
    {
      "action": "Edited",
      "date": "2016-07-15T17:06:42.012Z",
      "type": "_edit",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    },
    {
      "action": "Added",
      "date": "2016-07-15T17:06:41.371Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "rootEntity": {
    "id": "bqr7jmg37vqt",
    "name": "Publication Management - Home",
    "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt"
  },
  "mayCreateEntities": true,
  "isFavorite": false,
  "entityTree": {
    "id": "bqr7jmg37vqt",
    "name": "Publication Management - Home",
    "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt"
  },
  "name": "Publication Management",
  "permissions": {
    "contributors": [],
    "administrators": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ],
    "writers": [],
    "readers": []
  },
  "customFunctions": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
}

=== Creating entity types

Now that we have created the workspace the publication management system will store its contents in we can continue by creating two entity types required to store _publications_ prepared for and presented on multiple _conferences_.

==== Creating _publication_ entity type (POST)

To create an entity type in a workspace we simply concat the URI of the workspace by _/entityTypes_ and use the HTTP POST method to create a new entity type _publication_.

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg/entityTypes
BODY
{
    "name": "Publication"
}

*Response:*
[source,json]
{
  "processes": [],
  "attributeDefinitions": [],
  "taskDefinitions": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "entitiesCount": 0,
  "structurednessMetric": 1,
  "id": "dt56spnul01p",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T17:26:37.202Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "consistencyMetric": 1,
  "derivedAttributeDefinitions": [],
  "name": "Publication",
  "allowFreeAttributes": false,
  "associations": [],
  "incomingAssociations": [],
  "customFunctions": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
}

==== Creating _conference_ entity type (POST)

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg/entityTypes
BODY
{
    "name": "Conference"
}

*Response:*
[source,json]
{
  "processes": [],
  "attributeDefinitions": [],
  "taskDefinitions": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "entitiesCount": 0,
  "structurednessMetric": 1,
  "id": "19c48jgd4b8m2",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T17:29:20.655Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "consistencyMetric": 1,
  "derivedAttributeDefinitions": [],
  "name": "Conference",
  "allowFreeAttributes": false,
  "associations": [],
  "incomingAssociations": [],
  "customFunctions": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2"
}

Finally, we have our workspace and the two required entity types set up.
In the next steps we refine the attributes of the entity types before we start creating entities in the step after.

=== TODO: Creating attribute definitions

==== Creating _something_ attribute definitions (POST)


=== Creating entities

To create entities of the two entity types send HTTP POST requests to their endpoints, defined by their respective id.

==== Creating a _publication_ entity (POST)

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p/entities
BODY
{
    "name": "A sample paper"
}

*Response:*
[source,json]
{
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "tasks": [],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "incomingReferences": {},
  "creator": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "id": "15qr31m7ewuje",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T17:57:06.862Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "createdAt": "2016-07-15T17:57:06.000Z",
  "name": "A sample paper",
  "lastModifier": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "permissions": {
    "writers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ],
    "readers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ]
  },
  "attributes": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje",
  "lastModifiedAt": "2016-07-15T17:57:06.000Z"
}

==== Creating a _conference_ entity (POST)

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2/entities
BODY
{
    "name": "A sample conference"
}

*Response:*
[source,json]
{
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "tasks": [],
  "entityType": {
    "id": "19c48jgd4b8m2",
    "name": "Conference",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2"
  },
  "incomingReferences": {},
  "creator": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "id": "24ixbhft7i4b",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T18:00:49.440Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "createdAt": "2016-07-15T18:00:49.000Z",
  "name": "A sample conference",
  "lastModifier": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "permissions": {
    "writers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ],
    "readers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ]
  },
  "attributes": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/24ixbhft7i4b",
  "lastModifiedAt": "2016-07-15T18:00:49.000Z"
}

=== Getting entity types

==== Looking at all created entity types (GET)

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg/entityTypes

*Response:*
[source,json]
[
  {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  {
    "id": "19c48jgd4b8m2",
    "name": "Conference",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2"
  }
]

==== Looking at the _publication_ entity type (GET)

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p

*Response:*
[source,json]
{
  "processes": [],
  "attributeDefinitions": [],
  "taskDefinitions": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "entitiesCount": 0,
  "structurednessMetric": 1,
  "id": "dt56spnul01p",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T17:26:37.202Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "consistencyMetric": 1,
  "derivedAttributeDefinitions": [],
  "name": "Publication",
  "allowFreeAttributes": false,
  "associations": [],
  "incomingAssociations": [],
  "customFunctions": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
}

=== Getting attribute definitions

==== Looking at attribute definitions of entity type (GET)

==== Looking for entity type with attribute definition (GET)


=== Getting entities

==== Looking at all existing entities in workspace (GET)
*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg/entities

*Response:*
[source,json]
[
  {
    "id": "24ixbhft7i4b",
    "name": "A sample conference",
    "href": "https://server.sociocortex.com/api/v1/entities/24ixbhft7i4b"
  },
  {
    "id": "15qr31m7ewuje",
    "name": "A sample paper",
    "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje"
  },
  {
    "id": "bqr7jmg37vqt",
    "name": "Publication Management - Home",
    "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt"
  }
]

==== Looking at all existing entities of entity type _publication_ (GET)
*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p/entities

*Response:*
[source,json]
[
  {
    "id": "15qr31m7ewuje",
    "name": "A sample paper",
    "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje"
  }
]

==== Looking at single entity (GET)
*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje

*Response:*
[source,json]
{
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "tasks": [],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "incomingReferences": {},
  "creator": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "id": "15qr31m7ewuje",
  "versions": [
    {
      "action": "Added",
      "date": "2016-07-15T17:57:06.862Z",
      "type": "_new",
      "user": {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    }
  ],
  "createdAt": "2016-07-15T17:57:06.000Z",
  "name": "A sample paper",
  "lastModifier": {
    "id": "1tng2g7qgwd3k",
    "name": "Daniel Elsner",
    "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
  },
  "permissions": {
    "writers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ],
    "readers": [
      {
        "id": "1tng2g7qgwd3k",
        "name": "Daniel Elsner",
        "href": "https://server.sociocortex.com/api/v1/users/1tng2g7qgwd3k"
      }
    ]
  },
  "attributes": [],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje",
  "lastModifiedAt": "2016-07-15T17:57:06.000Z"
}

=== TODO: Getting tasks and task definitions

==== Create task definition (POST)

==== Create task (POST)

Set attribute (ideally bool) -> task gets completed


=== Searching for entities

==== Searching for entities in a workspace (GET)

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/searchResults?workspace=10sasph8dvxhg

*Response:*
[source,json]
{
  "results": [
    {
      "id": "dt56spnul01p",
      "name": "Publication",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p",
      "resourceType": "entityTypes"
    },
    {
      "id": "1bbxmsluu87f7",
      "name": "Text Page",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/1bbxmsluu87f7",
      "resourceType": "entityTypes"
    },
    {
      "id": "bqr7jmg37vqt",
      "name": "Publication Management - Home",
      "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt",
      "resourceType": "entities"
    },
    {
      "id": "10sasph8dvxhg",
      "name": "Publication Management",
      "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg",
      "resourceType": "workspaces"
    },
    {
      "id": "19c48jgd4b8m2",
      "name": "Conference",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2",
      "resourceType": "entityTypes"
    },
    {
      "id": "15qr31m7ewuje",
      "name": "A sample paper",
      "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje",
      "resourceType": "entities"
    },
    {
      "id": "24ixbhft7i4b",
      "name": "A sample conference",
      "href": "https://server.sociocortex.com/api/v1/entities/24ixbhft7i4b",
      "resourceType": "entities"
    }
  ],
  "totalCount": 7
}

==== Searching for entities with filter parameters (GET)
*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/searchResults?text=publication&workspace=10sasph8dvxhg&orderBy=alphabetically

*Response:*
[source,json]
{
  "results": [
    {
      "highlightedDisambiguation": "/<span class=\"sc-search-highlight\">Publication</span> Management/_",
      "id": "24ixbhft7i4b",
      "name": "A sample conference",
      "href": "https://server.sociocortex.com/api/v1/entities/24ixbhft7i4b",
      "resourceType": "entities"
    },
    {
      "highlightedDisambiguation": "/<span class=\"sc-search-highlight\">Publication</span> Management/_",
      "id": "15qr31m7ewuje",
      "name": "A sample paper",
      "href": "https://server.sociocortex.com/api/v1/entities/15qr31m7ewuje",
      "resourceType": "entities"
    },
    {
      "highlightedDisambiguation": "<span class=\"sc-search-highlight\">Publication</span> Management",
      "id": "19c48jgd4b8m2",
      "name": "Conference",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2",
      "resourceType": "entityTypes"
    },
    {
      "highlightedDisambiguation": "<span class=\"sc-search-highlight\">Publication</span> Management",
      "id": "dt56spnul01p",
      "highlightedName": "<span class=\"sc-search-highlight\">Publication</span>",
      "name": "Publication",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p",
      "resourceType": "entityTypes"
    },
    {
      "id": "10sasph8dvxhg",
      "highlightedName": "<span class=\"sc-search-highlight\">Publication</span> Management",
      "name": "Publication Management",
      "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg",
      "resourceType": "workspaces"
    },
    {
      "highlightedDisambiguation": "<span class=\"sc-search-highlight\">Publication</span> Management",
      "id": "bqr7jmg37vqt",
      "highlightedName": "<span class=\"sc-search-highlight\">Publication</span> Management - Home",
      "name": "Publication Management - Home",
      "href": "https://server.sociocortex.com/api/v1/entities/bqr7jmg37vqt",
      "resourceType": "entities"
    },
    {
      "highlightedDisambiguation": "<span class=\"sc-search-highlight\">Publication</span> Management",
      "id": "1bbxmsluu87f7",
      "name": "Text Page",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/1bbxmsluu87f7",
      "resourceType": "entityTypes"
    }
  ],
  "totalCount": 7
}

=== TODO: Updating entity type

==== Updating by adding new attribute definition (PUT)
==== Updating name of entity (PUT)
