Attributes of entity types can be linked to tasks, which means that for instance a task is not yet completed until a certain attribute it is linked to is set.
Task definitions create those links between attributes and tasks to be fulfilled.
In the following, we will first create a task definition for the previously defined _status_ attribute of the _publication_ entity type. Then, we create a new _publication_ entity whose status is not set to any value yet.
Last, the status of new entity is updated and set to _accepted_. This will fulfill the respective task.

==== Create task definition (POST)

For creating the task definition, we require the id of the previously defined entity type _publication_ as well as the id of the attribute definition of _Status_ which it contains. You need to replace them with your own values in order to make the requests work.

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/taskDefinitions
BODY
{
  "name": "Publication Status",
  "entityType": {
    "id":"dt56spnul01p"
  },
  "attributeDefinitions": [
    {
      "id":"mfpco2wx3zqp"
    }
  ]
}

*Response:*
[source,json]
{
  "attributeDefinitions": [
    {
      "id": "mfpco2wx3zqp",
      "versions": [],
      "readOnly": false,
      "name": "Status",
      "multiplicity": "maximalOne",
      "attributeType": "Enumeration",
      "entityType": {
        "id": "dt56spnul01p",
        "name": "Publication",
        "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
      },
      "href": "https://server.sociocortex.com/api/v1/attributeDefinitions/mfpco2wx3zqp",
      "options": {
        "enumerationValues": [
          "Planned",
          "Submitted",
          "Accepted"
        ]
      }
    }
  ],
  "id": "875jp376lljp",
  "satisfies": [],
  "name": "Publication Status",
  "tasks": [],
  "preconditions": [],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "href": "https://server.sociocortex.com/api/v1/taskDefinitions/875jp376lljp"
}

==== Create entity _publication_ (POST)

Next, we create a new publication where we purposefully do not set all the defined attributes yet.

*Request:*
[source,bash]
POST https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p/entities
BODY
{
    "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
    "attributes":[
        {
            "name":"acceptedIn",
            "values":[]
        },
        {
            "name":"Abstract",
            "values": ["Knowledge work is becoming the predominant type of work in many countries and is involved in the most important processes in organizations. ..."]
        },
        {
            "name":"Status",
            "values":[]
        },
        {
            "name":"authors",
            "values":[]
        }
    ]
}

*Response:*
[source,json]
{
  "isOverdue": false,
  "progress": 0,
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "isInconsistent": false,
  "tasks": [
    {
      "expertises": [],
      "isOverdue": false,
      "progress": 0,
      "id": "1jxlh7fiinyp3",
      "taskDefinition": {
        "id": "875jp376lljp",
        "name": "Publication Status",
        "href": "https://server.sociocortex.com/api/v1/taskDefinitions/875jp376lljp"
      },
      "skipped": false,
      "isProgressCalculated": true,
      "entity": {
        "id": "pvv5b7tg2ave",
        "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
        "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave"
      },
      "name": "Publication Status",
      "attributes": [
        {
          "id": "1nnq4l3r7xiez",
          "name": "Status",
          "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
        }
      ],
      "isInconsistent": false,
      "href": "https://server.sociocortex.com/api/v1/tasks/1jxlh7fiinyp3"
    }
  ],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "incomingReferences": {},
  "creator": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "id": "pvv5b7tg2ave",
  "versions": ["..."],
  "createdAt": "2016-07-25T12:12:42.000Z",
  "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
  "lastModifier": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "permissions": {
    "writers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ],
    "readers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ]
  },
  "attributes": [
    {
      "id": "1fxaj2nfs3yp9",
      "values": [],
      "name": "authors",
      "href": "https://server.sociocortex.com/api/v1/attributes/1fxaj2nfs3yp9"
    },
    {
      "id": "1nnq4l3r7xiez",
      "values": [],
      "name": "Status",
      "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
    },
    {
      "id": "1r36ijukwwbtf",
      "values": [],
      "name": "acceptedIn",
      "href": "https://server.sociocortex.com/api/v1/attributes/1r36ijukwwbtf"
    },
    {
      "id": "1rc9u2if7o62m",
      "values": [
        "Knowledge work is becoming the predominant type of work in many countries and is involved in the most important processes in organizations. ..."
      ],
      "name": "Abstract",
      "href": "https://server.sociocortex.com/api/v1/attributes/1rc9u2if7o62m"
    }
  ],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave",
  "lastModifiedAt": "2016-07-25T12:12:42.000Z"
}

==== Updating status of publication (PUT)

If we look at the entity we just created, we can see a task list being attached to it with one open task concerning the taskDefinition we created before. Its progress is 0 and thus the task is not yet fulfilled.

*Request:*
[source,bash]
GET https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave

*Response:*
[source,json]
{
  "isOverdue": false,
  "progress": 0,
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "isInconsistent": false,
  "tasks": [
    {
      "expertises": [],
      "isOverdue": false,
      "progress": 0,
      "id": "1jxlh7fiinyp3",
      "taskDefinition": {
        "id": "875jp376lljp",
        "name": "Publication Status",
        "href": "https://server.sociocortex.com/api/v1/taskDefinitions/875jp376lljp"
      },
      "skipped": false,
      "isProgressCalculated": true,
      "entity": {
        "id": "pvv5b7tg2ave",
        "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
        "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave"
      },
      "name": "Publication Status",
      "attributes": [
        {
          "id": "1nnq4l3r7xiez",
          "name": "Status",
          "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
        }
      ],
      "isInconsistent": false,
      "href": "https://server.sociocortex.com/api/v1/tasks/1jxlh7fiinyp3"
    }
  ],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "incomingReferences": {},
  "creator": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "id": "pvv5b7tg2ave",
  "versions": ["..."],
  "createdAt": "2016-07-25T12:12:42.000Z",
  "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
  "lastModifier": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "permissions": {
    "writers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ],
    "readers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ]
  },
  "attributes": [
    {
      "id": "1fxaj2nfs3yp9",
      "values": [],
      "name": "authors",
      "href": "https://server.sociocortex.com/api/v1/attributes/1fxaj2nfs3yp9"
    },
    {
      "id": "1nnq4l3r7xiez",
      "values": [],
      "name": "Status",
      "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
    },
    {
      "id": "1r36ijukwwbtf",
      "values": [],
      "name": "acceptedIn",
      "href": "https://server.sociocortex.com/api/v1/attributes/1r36ijukwwbtf"
    },
    {
      "id": "1rc9u2if7o62m",
      "values": [
        "Knowledge work is becoming the predominant type of work in many countries and is involved in the most important processes in organizations. ..."
      ],
      "name": "Abstract",
      "href": "https://server.sociocortex.com/api/v1/attributes/1rc9u2if7o62m"
    }
  ],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave",
  "lastModifiedAt": "2016-07-25T12:12:42.000Z"
}

In order to fulfill the task we update the concurrent entity by using the HTTP PUT method to change the _status_ to _Accepted_. The response contains the updated entity with a progress of the task of 100 which means it is fulfilled.

*Request:*
[source,bash]
PUT https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave
BODY
{
    "attributes":[
        {
            "id": "1nnq4l3r7xiez",
            "name":"Status",
            "values": ["Accepted"]
        }
    ]
}

*Response:*
[source,json]
{
  "isOverdue": false,
  "progress": 100,
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "isInconsistent": false,
  "tasks": [
    {
      "progress": 100,
      "isOverdue": false,
      "taskDefinition": {
        "id": "875jp376lljp",
        "name": "Publication Status",
        "href": "https://server.sociocortex.com/api/v1/taskDefinitions/875jp376lljp"
      },
      "entity": {
        "id": "pvv5b7tg2ave",
        "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
        "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave"
      },
      "isProgressCalculated": true,
      "isInconsistent": false,
      "expertises": [],
      "id": "1jxlh7fiinyp3",
      "skipped": false,
      "name": "Publication Status",
      "finishedAt": "2016-07-26T07:22:35.000Z",
      "finishedBy": {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      },
      "attributes": [
        {
          "id": "1nnq4l3r7xiez",
          "name": "Status",
          "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
        }
      ],
      "href": "https://server.sociocortex.com/api/v1/tasks/1jxlh7fiinyp3"
    }
  ],
  "entityType": {
    "id": "dt56spnul01p",
    "name": "Publication",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
  },
  "incomingReferences": {},
  "creator": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "id": "pvv5b7tg2ave",
  "versions": ["..."],
  "createdAt": "2016-07-25T12:12:42.000Z",
  "name": "Ha15a - Empowering End-Users to Collaboratively Structure Processes for Knowledge Work",
  "lastModifier": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "permissions": {
    "writers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ],
    "readers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ]
  },
  "attributes": [
    {
      "id": "1fxaj2nfs3yp9",
      "values": [],
      "name": "authors",
      "href": "https://server.sociocortex.com/api/v1/attributes/1fxaj2nfs3yp9"
    },
    {
      "id": "1nnq4l3r7xiez",
      "values": [
        "Accepted"
      ],
      "name": "Status",
      "href": "https://server.sociocortex.com/api/v1/attributes/1nnq4l3r7xiez"
    },
    {
      "id": "1r36ijukwwbtf",
      "values": [],
      "name": "acceptedIn",
      "href": "https://server.sociocortex.com/api/v1/attributes/1r36ijukwwbtf"
    },
    {
      "id": "1rc9u2if7o62m",
      "values": [
        "Knowledge work is becoming the predominant type of work in many countries and is involved in the most important processes in organizations. ..."
      ],
      "name": "Abstract",
      "href": "https://server.sociocortex.com/api/v1/attributes/1rc9u2if7o62m"
    }
  ],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/pvv5b7tg2ave",
  "lastModifiedAt": "2016-07-25T12:12:42.000Z"
}
