
==== Updating name of entity (PUT)

The easiest way to demonstrate how entities are updated is by sending a HTTP PUT request on an existing _conference_ which is supposed to change the name of the conference. Let's assume we just want to get rid of the abbreviation of the conference (ICSE).

*Request:*
[source,bash]
PUT https://server.sociocortex.com/api/v1/entities/n6eidlmr0by7
{
    "name":"International Conference on Software Engineering"
}

*Response:*
[source,json]
{
  "files": [],
  "workspace": {
    "id": "10sasph8dvxhg",
    "name": "Publication Management",
    "href": "https://server.sociocortex.com/api/v1/workspaces/10sasph8dvxhg"
  },
  "children": [],
  "tasks": [],
  "entityType": {
    "id": "19c48jgd4b8m2",
    "name": "Conference",
    "href": "https://server.sociocortex.com/api/v1/entityTypes/19c48jgd4b8m2"
  },
  "incomingReferences": {
    "acceptedIn": [
      {
        "id": "127trtufzdgcw",
        "name": "Re16a - Lessons Learned in Aligning Data and Model Evolution in Collaborative Information Systems",
        "href": "https://server.sociocortex.com/api/v1/entities/127trtufzdgcw"
      }
    ]
  },
  "creator": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "id": "n6eidlmr0by7",
  "versions": ["..."],
  "createdAt": "2016-07-24T11:12:00.000Z",
  "name": "International Conference on Software Engineering",
  "lastModifier": {
    "id": "$USER_ID",
    "name": "$NAME",
    "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
  },
  "permissions": {
    "writers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ],
    "readers": [
      {
        "id": "$USER_ID",
        "name": "$NAME",
        "href": "https://server.sociocortex.com/api/v1/users/$USER_ID"
      }
    ]
  },
  "attributes": [
    {
      "id": "pme5rnjsvx5z",
      "values": [
        "A"
      ],
      "name": "Rank",
      "href": "https://server.sociocortex.com/api/v1/attributes/pme5rnjsvx5z"
    },
    {
      "id": "voa7iqjet7pf",
      "values": [
        2016
      ],
      "name": "Year",
      "href": "https://server.sociocortex.com/api/v1/attributes/voa7iqjet7pf"
    }
  ],
  "mayEdit": true,
  "href": "https://server.sociocortex.com/api/v1/entities/n6eidlmr0by7",
  "lastModifiedAt": "2016-07-24T18:18:06.000Z"
}

==== Updating single attribute of entity (PUT)

As attributes might change over time, it might be necessary to change an attribute of an entity at some point. This can be done by sending a HTTP PUT request to a certain attribute identified by its id. The latter can be found out by querying the respective entity first (see <<Looking at single entity (GET)>>). Let's assume we want to change the authors of the _publication_ created in <<Create entity _publication_ (POST)>> where in our case the id of the authors attribute is 1fxaj2nfs3yp9.

*Request:*
[source,bash]
PUT https://server.sociocortex.com/api/v1/attributes/1fxaj2nfs3yp9
BODY
{
    "values":[{
        "id":"1d94htksgwy2i",
        "name": "Matheus Hauder"
    }]
}

*Response:*
[source,json]
{
  "id": "1fxaj2nfs3yp9",
  "values": [
    {
      "id": "1d94htksgwy2i",
      "name": "Matheus Hauder",
      "href": "https://server.sociocortex.com/api/v1/users/1d94htksgwy2i"
    }
  ],
  "attributeDefinition": {
    "id": "18b1hu00gnxdi",
    "versions": [],
    "readOnly": false,
    "name": "authors",
    "multiplicity": "any",
    "attributeType": "Link",
    "entityType": {
      "id": "dt56spnul01p",
      "name": "Publication",
      "href": "https://server.sociocortex.com/api/v1/entityTypes/dt56spnul01p"
    },
    "href": "https://server.sociocortex.com/api/v1/attributeDefinitions/18b1hu00gnxdi",
    "options": {
      "resourceType": "users"
    }
  },
  "name": "authors",
  "href": "https://server.sociocortex.com/api/v1/attributes/1fxaj2nfs3yp9"
}
